/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as RecrutamentoInternoRouteImport } from './routes/recrutamento-interno'
import { Route as RecrutamentoRouteImport } from './routes/recrutamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasJobIdRouteImport } from './routes/vagas.$jobId'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutamentoInternoRoute = RecrutamentoInternoRouteImport.update({
  id: '/recrutamento-interno',
  path: '/recrutamento-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutamentoRoute = RecrutamentoRouteImport.update({
  id: '/recrutamento',
  path: '/recrutamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasJobIdRoute = VagasJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => VagasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/recrutamento-interno': typeof RecrutamentoInternoRoute
  '/simulacao': typeof SimulacaoRoute
  '/supervisor': typeof SupervisorRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/recrutamento-interno': typeof RecrutamentoInternoRoute
  '/simulacao': typeof SimulacaoRoute
  '/supervisor': typeof SupervisorRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/recrutamento-interno': typeof RecrutamentoInternoRoute
  '/simulacao': typeof SimulacaoRoute
  '/supervisor': typeof SupervisorRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atendimento'
    | '/dashboard'
    | '/login'
    | '/recrutamento'
    | '/recrutamento-interno'
    | '/simulacao'
    | '/supervisor'
    | '/vagas'
    | '/vagas/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/atendimento'
    | '/dashboard'
    | '/login'
    | '/recrutamento'
    | '/recrutamento-interno'
    | '/simulacao'
    | '/supervisor'
    | '/vagas'
    | '/vagas/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atendimento'
    | '/dashboard'
    | '/login'
    | '/recrutamento'
    | '/recrutamento-interno'
    | '/simulacao'
    | '/supervisor'
    | '/vagas'
    | '/vagas/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtendimentoRoute: typeof AtendimentoRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RecrutamentoRoute: typeof RecrutamentoRoute
  RecrutamentoInternoRoute: typeof RecrutamentoInternoRoute
  SimulacaoRoute: typeof SimulacaoRoute
  SupervisorRoute: typeof SupervisorRoute
  VagasRoute: typeof VagasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutamento-interno': {
      id: '/recrutamento-interno'
      path: '/recrutamento-interno'
      fullPath: '/recrutamento-interno'
      preLoaderRoute: typeof RecrutamentoInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutamento': {
      id: '/recrutamento'
      path: '/recrutamento'
      fullPath: '/recrutamento'
      preLoaderRoute: typeof RecrutamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$jobId': {
      id: '/vagas/$jobId'
      path: '/$jobId'
      fullPath: '/vagas/$jobId'
      preLoaderRoute: typeof VagasJobIdRouteImport
      parentRoute: typeof VagasRoute
    }
  }
}

interface VagasRouteChildren {
  VagasJobIdRoute: typeof VagasJobIdRoute
}

const VagasRouteChildren: VagasRouteChildren = {
  VagasJobIdRoute: VagasJobIdRoute,
}

const VagasRouteWithChildren = VagasRoute._addFileChildren(VagasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtendimentoRoute: AtendimentoRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RecrutamentoRoute: RecrutamentoRoute,
  RecrutamentoInternoRoute: RecrutamentoInternoRoute,
  SimulacaoRoute: SimulacaoRoute,
  SupervisorRoute: SupervisorRoute,
  VagasRoute: VagasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
