/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as RecrutamentoRouteImport } from './routes/recrutamento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasJobIdRouteImport } from './routes/vagas.$jobId'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutamentoRoute = RecrutamentoRouteImport.update({
  id: '/recrutamento',
  path: '/recrutamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasJobIdRoute = VagasJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => VagasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/simulacao': typeof SimulacaoRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/simulacao': typeof SimulacaoRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recrutamento': typeof RecrutamentoRoute
  '/simulacao': typeof SimulacaoRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/recrutamento'
    | '/simulacao'
    | '/vagas'
    | '/vagas/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/recrutamento'
    | '/simulacao'
    | '/vagas'
    | '/vagas/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/recrutamento'
    | '/simulacao'
    | '/vagas'
    | '/vagas/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RecrutamentoRoute: typeof RecrutamentoRoute
  SimulacaoRoute: typeof SimulacaoRoute
  VagasRoute: typeof VagasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutamento': {
      id: '/recrutamento'
      path: '/recrutamento'
      fullPath: '/recrutamento'
      preLoaderRoute: typeof RecrutamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$jobId': {
      id: '/vagas/$jobId'
      path: '/$jobId'
      fullPath: '/vagas/$jobId'
      preLoaderRoute: typeof VagasJobIdRouteImport
      parentRoute: typeof VagasRoute
    }
  }
}

interface VagasRouteChildren {
  VagasJobIdRoute: typeof VagasJobIdRoute
}

const VagasRouteChildren: VagasRouteChildren = {
  VagasJobIdRoute: VagasJobIdRoute,
}

const VagasRouteWithChildren = VagasRoute._addFileChildren(VagasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RecrutamentoRoute: RecrutamentoRoute,
  SimulacaoRoute: SimulacaoRoute,
  VagasRoute: VagasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
