/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasJobIdRouteImport } from './routes/vagas.$jobId'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasJobIdRoute = VagasJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => VagasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/testes': typeof TestesRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/testes': typeof TestesRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/testes': typeof TestesRoute
  '/vagas': typeof VagasRouteWithChildren
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/testes' | '/vagas' | '/vagas/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/testes' | '/vagas' | '/vagas/$jobId'
  id: '__root__' | '/' | '/admin' | '/testes' | '/vagas' | '/vagas/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TestesRoute: typeof TestesRoute
  VagasRoute: typeof VagasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$jobId': {
      id: '/vagas/$jobId'
      path: '/$jobId'
      fullPath: '/vagas/$jobId'
      preLoaderRoute: typeof VagasJobIdRouteImport
      parentRoute: typeof VagasRoute
    }
  }
}

interface VagasRouteChildren {
  VagasJobIdRoute: typeof VagasJobIdRoute
}

const VagasRouteChildren: VagasRouteChildren = {
  VagasJobIdRoute: VagasJobIdRoute,
}

const VagasRouteWithChildren = VagasRoute._addFileChildren(VagasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TestesRoute: TestesRoute,
  VagasRoute: VagasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
